-- MySQL Script generated by MySQL Workbench
-- Thu Nov  7 13:13:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema thunder_gears
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema thunder_gears
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `thunder_gears` DEFAULT CHARACTER SET utf8 ;
USE `thunder_gears` ;

-- -----------------------------------------------------
-- Table `thunder_gears`.`cliente`
-- -----------------------------------------------------
-- Tabela Cliente
CREATE TABLE IF NOT EXISTS `thunder_gears`.`cliente` (
  `ID_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `telefone` CHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`ID_cliente`)
) ENGINE = InnoDB;

-- Tabela Funcionário
CREATE TABLE IF NOT EXISTS `thunder_gears`.`funcionario` (
  `ID_funcionario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `telefone` CHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(30) NOT NULL,
  `data_admissao` DATE NOT NULL,
  `data_demissao` DATE,
  `salario` DECIMAL(10,2) NOT NULL,
  `status` VARCHAR(10),
  `foto_perfil` BLOB,
  PRIMARY KEY (`ID_funcionario`)
) ENGINE = InnoDB;

-- Tabela Moto
CREATE TABLE IF NOT EXISTS `thunder_gears`.`moto` (
  `ID_moto` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(50) NOT NULL,
  `modelo` VARCHAR(50) NOT NULL,
  `combustivel` VARCHAR(20) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `ano` INT NOT NULL,
  `potencia_cavalos` INT,
  `consumo_km` VARCHAR(20),
  `estoque` INT NOT NULL,
  `foto_moto` BLOB,
  PRIMARY KEY (`ID_moto`)
) ENGINE = InnoDB;

-- Tabela Quantidade_vendida
CREATE TABLE IF NOT EXISTS `thunder_gears`.`quantidade_vendida` (
  `ID_quantidade_vendida` INT NOT NULL AUTO_INCREMENT,
  `ID_venda` INT NOT NULL,
  `ID_moto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`ID_quantidade_vendida`),
  FOREIGN KEY (`ID_venda`) REFERENCES `venda`(`ID_venda`),
  FOREIGN KEY (`ID_moto`) REFERENCES `moto`(`ID_moto`)
) ENGINE = InnoDB;

-- Tabela Vendas
CREATE TABLE IF NOT EXISTS `thunder_gears`.`venda` (
  `ID_venda` INT NOT NULL AUTO_INCREMENT,
  `metodo_pagamento` VARCHAR(20) NOT NULL,
  `valor_total_venda` DECIMAL(10,2) NOT NULL,
  `data_venda` DATE NOT NULL,
  `ID_cliente` INT NOT NULL,
  `ID_funcionario` INT NOT NULL,
  PRIMARY KEY (`ID_venda`),
  FOREIGN KEY (`ID_cliente`) REFERENCES `cliente`(`ID_cliente`),
  FOREIGN KEY (`ID_funcionario`) REFERENCES `funcionario`(`ID_funcionario`)
) ENGINE = InnoDB;

-- Tabela Endereço
CREATE TABLE IF NOT EXISTS `thunder_gears`.`endereco` (
  `ID_endereco` INT NOT NULL AUTO_INCREMENT,
  `cep` CHAR(8) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `avenida` VARCHAR(100),
  PRIMARY KEY (`ID_endereco`)
) ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
