-- MySQL Script generated by MySQL Workbench
-- Thu Nov  7 13:13:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema thunder_gears
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema thunder_gears
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `thunder_gears` DEFAULT CHARACTER SET utf8 ;
USE `thunder_gears` ;

-- -----------------------------------------------------
-- Table `thunder_gears`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thunder_gears`.`cliente` (
  `ID_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `telefone` CHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`ID_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thunder_gears`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thunder_gears`.`funcionario` (
  `ID_funcionario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `telefone` CHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `data_admissao` DATE NOT NULL,
  `data_demissao` DATE NULL,
  `salario` DECIMAL(10,3) NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thunder_gears`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thunder_gears`.`venda` (
  `ID_venda` INT NOT NULL AUTO_INCREMENT,
  `forma_pagamento` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(10,3) NOT NULL,
  `data` DATE NOT NULL,
  `ID_funcionario` INT NOT NULL,
  `ID_cliente` INT NOT NULL,
  PRIMARY KEY (`ID_venda`, `ID_funcionario`, `ID_cliente`),
    FOREIGN KEY (`ID_funcionario`)
    REFERENCES `thunder_gears`.`funcionario` (`ID_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`ID_cliente`)
    REFERENCES `thunder_gears`.`cliente` (`ID_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thunder_gears`.`moto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `thunder_gears`.`moto` (
  `ID_moto` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `tipo_motor` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,3) NOT NULL,
  `potencia_cavalos` VARCHAR(10) NOT NULL,
  `consumo_km` VARCHAR(10) NOT NULL,
  `ID_venda` INT NULL,
  `ID_funcionario` INT NULL,
  PRIMARY KEY (`ID_moto`),
    FOREIGN KEY (`ID_venda` , `ID_funcionario`)
    REFERENCES `thunder_gears`.`venda` (`ID_venda` , `ID_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
